### ISSUE TITLE
Markdown: video embedding

### ISSUE THREAD

**Issue by boyeln** [RadioRevolt/dokuspokus#10]
Avhengigheter: #6 

En shortcode som embedder youtube, vimeo og liknende responsivt.

Foreslått syntaks: `[[youtube <id>]]`

Eksempel:

```
[[youtube wE3fmFTtP9g]]
```

Gir:

``` html
<div class="videoWrapper">
    <iframe width="420" height="315"
        src="http://www.youtube.com/embed/wE3fmFTtP9g">
    </iframe>
</div>
```

Krever CSS for videoWrapper-klassen:

``` css
.videoWrapper {
    position: relative;
    padding-bottom: 56.25%; /* 16:9 */
    height: 0;
}
.videoWrapper iframe {
    position: absolute;
    border: 0;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```
